# Pubky Rooms release image. Build context is the repository root because the
# app (`pubky_rooms/`) depends on the sibling library (`pubky_ex/`) as a path
# dependency: both directories are copied into the builder.
#
# Generated by `mix phx.gen.release --docker` (Phoenix 1.8) and adapted for the
# two-directory layout; the release itself is standard (`mix release`, started
# by `rel/overlays/bin/server`, which sets PHX_SERVER). Runtime configuration
# comes from environment variables read in `pubky_rooms/config/runtime.exs`
# (see docs/operations.md, "Deploy targets").
#
# Image tags come from Hex's build server: https://bob.hex.pm/docker
#   builder: docker.io/hexpm/elixir:1.18.3-erlang-27.3.4.6-debian-trixie-20260610-slim
#   runner:  docker.io/debian:trixie-20260610-slim
# Keep the same Debian release for both stages.

ARG ELIXIR_VERSION=1.18.3
ARG OTP_VERSION=27.3.4.6
ARG DEBIAN_VERSION=trixie-20260610-slim

ARG BUILDER_IMAGE="docker.io/hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"
ARG RUNNER_IMAGE="docker.io/debian:${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE} AS builder

# build dependencies (git fetches the lucide icon set)
RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential git \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mix local.hex --force \
  && mix local.rebar --force

ENV MIX_ENV="prod"

# the library the app depends on by path (../pubky_ex from the app directory)
COPY pubky_ex/mix.exs pubky_ex/mix.lock pubky_ex/
COPY pubky_ex/lib pubky_ex/lib

# app dependencies first, so they are cached across source changes
COPY pubky_rooms/mix.exs pubky_rooms/mix.lock pubky_rooms/
WORKDIR /app/pubky_rooms
RUN mix deps.get --only $MIX_ENV
RUN mkdir config

# compile-time config before the dependencies compile, so a config change
# recompiles them
COPY pubky_rooms/config/config.exs pubky_rooms/config/${MIX_ENV}.exs config/
RUN mix deps.compile

# tailwind and esbuild binaries
RUN mix assets.setup

COPY pubky_rooms/priv priv
COPY pubky_rooms/lib lib

RUN mix compile

COPY pubky_rooms/assets assets

# minified CSS/JS and the digested static files (fonts, images, the share image)
RUN mix assets.deploy

# runtime config changes do not recompile the code
COPY pubky_rooms/config/runtime.exs config/

COPY pubky_rooms/rel rel
RUN mix release

# ── runtime image: the release and nothing else ──────────────────────────────
FROM ${RUNNER_IMAGE} AS final

RUN apt-get update \
  && apt-get install -y --no-install-recommends libstdc++6 openssl libncurses6 locales ca-certificates \
  && rm -rf /var/lib/apt/lists/*

RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
  && locale-gen

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

WORKDIR "/app"
RUN chown nobody /app

# the room directory (DETS) lives here; in production a volume is mounted at
# this path (PUBKY_DATA_DIR=/data)
RUN mkdir -p /data && chown nobody /data

ENV MIX_ENV="prod"

COPY --from=builder --chown=nobody:root /app/pubky_rooms/_build/${MIX_ENV}/rel/pubky_rooms ./

USER nobody

CMD ["/app/bin/server"]
