defmodule PubkyRoomsWeb.UI.Icon do
  @moduledoc """
  Lucide icons and Pubky brand marks.

  Icons are rendered as CSS masks generated by `assets/vendor/lucide.js` from
  the `:lucide` dependency, so any icon at https://lucide.dev is available as
  `lucide-<name>` and takes its color from `currentColor`.
  """
  use Phoenix.Component

  use Phoenix.VerifiedRoutes,
    endpoint: PubkyRoomsWeb.Endpoint,
    router: PubkyRoomsWeb.Router,
    statics: PubkyRoomsWeb.static_paths()

  @doc """
  Renders a Lucide icon.

      <.icon name="lucide-house" />
      <.icon name="lucide-send" class="size-5 text-brand" />
  """
  attr :name, :string, required: true, doc: "a `lucide-*` icon name"
  attr :class, :any, default: "size-4"
  attr :rest, :global

  def icon(%{name: "lucide-" <> _} = assigns) do
    ~H"""
    <span class={[@name, @class]} aria-hidden="true" {@rest} />
    """
  end

  @doc """
  The Pubky wordmark with the lime key, followed by a product name.

  The product name is typeset to sit on the wordmark's own baseline. In the
  36 px SVG the letters of "Pubky" have their baseline 29 px from the top and
  an x-height of 14 px, which is Inter Tight Bold at 26 px. The text box is
  bottom-aligned to the image with a line-height of 33 px (2.0625 rem): with
  the font's ascent (0.969 em, 25 px) and descent (0.241 em, 6 px) the
  browser puts the text baseline at 36 - 33 + (33 - 31) / 2 + 25 = 29 px.
  Change the three numbers together if the logo SVG or the typeface changes.

      <.logo />                 # Pubky Rooms
      <.logo product={nil} />   # Pubky only
  """
  attr :product, :string, default: "Rooms"
  attr :class, :any, default: nil
  attr :rest, :global, include: ~w(href navigate)

  def logo(assigns) do
    ~H"""
    <.link class={["inline-flex items-end gap-1.5 select-none", @class]} {@rest}>
      <img src={~p"/images/pubky-logo.svg"} alt="Pubky" width="109" height="36" class="h-9 w-auto" />
      <span
        :if={@product}
        class="text-brand text-[1.625rem] leading-[2.0625rem] font-bold tracking-tight"
      >
        {@product}
      </span>
    </.link>
    """
  end

  @doc "The Pubky key mark alone (lime), for compact placements."
  attr :class, :any, default: "size-8"
  attr :rest, :global

  def pubky_mark(assigns) do
    ~H"""
    <img src={~p"/images/pubky-favicon.svg"} alt="" class={@class} {@rest} />
    """
  end
end
