defmodule PubkyRoomsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :pubky_rooms

  # The session cookie carries the user's Pubky grant credential (see
  # PubkyRooms.Auth.SessionStore), so it is encrypted as well as signed,
  # httpOnly (Plug default), SameSite=Lax, 30 days, and HTTPS-only in prod.
  @session_options [
    store: :cookie,
    key: "_pubky_rooms_key",
    signing_salt: "Km7PKZQ6",
    encryption_salt: "R4x0pQ9vL2mD",
    same_site: "Lax",
    max_age: 60 * 60 * 24 * 30,
    secure: Application.compile_env(:pubky_rooms, :secure_cookies, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, :x_headers, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :x_headers, session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :pubky_rooms,
    gzip: not code_reloading?,
    only: PubkyRoomsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  # Request lines go to `debug`: room paths carry public keys, which must not
  # appear in logs at `info` and above (ADR 0006). Durations are still measured
  # through the telemetry events; the platform keeps its own access log.
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint], log: :debug

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PubkyRoomsWeb.Router
end
